# Libraries and Imports


In [6]:
from keras.models import *
from keras.layers import *
from keras import Input
from keras import Sequential
from tensorflow import keras
from keras import metrics

import pandas as pd

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

import numpy as np                      

from PIL import Image, ImageOps
from matplotlib import pyplot as plt    
import cv2
import math
import sys
import mariadb

ModuleNotFoundError: ignored

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pip install mariadb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached mariadb-1.1.5.post2.tar.gz (82 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Using cached mariadb-1.1.5.post1.tar.gz (82 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Using cached mariadb-1.1.5.tar.gz (81 kB)


# Create Dataset

In [ ]:
path = "ResizedSetV3Binary"
dir_list = os.listdir(path)
 
print("Files and directories in '", path, "' :")
print(len(dir_list))

Files and directories in ' ResizedSetV3Binary ' :
34


In [ ]:
# Resize all pictures
for item in dir_list:
    print(item)
    im = Image.open("ContainerTrain/"+item)
    f, e = os.path.splitext(item)
    imResize = im.resize((300,420), Image.ANTIALIAS)
    imResize.save("ResizedSetV1/"+f + '.jpg', 'JPEG', quality=90)

ConE1652.jpg
ConM6729.jpg
ConE1646.jpg
ConE1493.jpg
ConL6089.jpg
ConE1487.jpg
ConL5225.jpg
ConL5231.jpg
ConH4523.jpg
ConL5219.jpg
ConH4245.jpg
ConL6076.jpg
ConH4251.jpg
ConM7796.jpg
ConM7782.jpg
ConE1242.jpg
ConM6339.jpg
ConM7769.jpg
ConF3031.jpg
ConF2449.jpg
ConF3025.jpg
ConF3019.jpg
ConH4669.jpg
ConE989.jpg
ConE988.jpg


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/760285351.py:5: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


ConH4668.jpg
ConF3018.jpg
ConF3024.jpg
ConF3030.jpg
ConF2448.jpg
ConM7768.jpg
ConM6338.jpg
ConE1243.jpg
ConM7783.jpg
ConM7797.jpg
ConH4250.jpg
ConL5218.jpg
ConH4522.jpg
ConL6077.jpg
ConH4244.jpg
ConL5230.jpg
ConL5224.jpg
ConE1486.jpg
ConL6088.jpg
ConE1492.jpg
ConM6728.jpg
ConE1647.jpg
ConE1653.jpg
ConE1645.jpg
ConE1651.jpg
ConE1484.jpg
ConE1490.jpg
ConL5226.jpg
ConH4252.jpg
ConH4246.jpg
ConL6075.jpg
ConH4520.jpg
ConM7781.jpg
ConM7795.jpg
ConE1255.jpg
ConE1241.jpg
ConE236.jpg
ConF3026.jpg
ConF3032.jpg
ConH4680.jpg
ConF3033.jpg
ConF3027.jpg
ConE237.jpg
ConE1254.jpg
ConM7794.jpg
ConM7780.jpg
ConL6074.jpg
ConH4247.jpg
ConH4521.jpg
ConH4253.jpg
ConL5227.jpg
ConH4509.jpg
ConE1491.jpg
ConE1485.jpg
ConE1650.jpg
ConE1644.jpg
ConE1640.jpg
ConE1654.jpg
ConE1495.jpg
ConH4257.jpg
ConH4525.jpg
ConL6070.jpg
ConL5223.jpg
ConH4519.jpg
ConM7784.jpg
ConM7790.jpg
ConE1250.jpg
ConE1244.jpg
ConH4848.jpg
ConF3023.jpg
ConF3037.jpg
ConF3036.jpg
ConF3022.jpg
ConH4849.jpg
ConE1245.jpg
ConE1251.jpg
ConM7791.jpg
C

In [ ]:
# Make txt File
f = open("dataFinalSubBinary.txt", "w")
count = 0
for i in dir_list:
    count+=1
    label = i[3:4]
    path = "ResizedSetV3Binary/" + i

    temp = path+','+label
    print(temp)

    f.write(path+","+label+" \n")

print(count)
f.close

ResizedSetV3Binary/ConE1255.jpg,E
ResizedSetV3Binary/ConE6089.jpg,E
ResizedSetV3Binary/ConE5230.jpg,E
ResizedSetV3Binary/ConH2781.jpg,H
ResizedSetV3Binary/.DS_Store,_
ResizedSetV3Binary/ConH6736.jpg,H
ResizedSetV3Binary/ConH3465.jpg,H
ResizedSetV3Binary/ConH4526.jpg,H
ResizedSetV3Binary/ConH3314.jpg,H
ResizedSetV3Binary/ConH3039.jpg,H
ResizedSetV3Binary/ConH7061.jpg,H
ResizedSetV3Binary/ConH2454.jpg,H
ResizedSetV3Binary/ConE1803.jpg,E
ResizedSetV3Binary/ConH7315.jpg,H
ResizedSetV3Binary/ConH3775.jpg,H
ResizedSetV3Binary/ConH6351.jpg,H
ResizedSetV3Binary/ConH3024.jpg,H
ResizedSetV3Binary/ConE263.jpg,E
ResizedSetV3Binary/ConE1003.jpg,E
ResizedSetV3Binary/ConE5715.jpg,E
ResizedSetV3Binary/ConE5463.jpg,E
ResizedSetV3Binary/ConE499.jpg,E
ResizedSetV3Binary/ConE739.jpg,E
ResizedSetV3Binary/ConE5935.jpg,E
ResizedSetV3Binary/ConH4996.jpg,H
ResizedSetV3Binary/ConH3791.jpg,H
ResizedSetV3Binary/ConH4264.jpg,H
ResizedSetV3Binary/ConH7779.jpg,H
ResizedSetV3Binary/ConH4847.jpg,H
ResizedSetV3Binary/C

<function TextIOWrapper.close()>

# Data and Preprocessing

In [ ]:
path = 'dataFinalSubBinary.txt'
# path = 'data.txt'

In [ ]:
data = pd.read_csv(path)

In [ ]:
data

Files Label
0   ResizedSetV3Binary/ConE1255.jpg     E
1   ResizedSetV3Binary/ConE6089.jpg     E
2   ResizedSetV3Binary/ConE5230.jpg     E
3   ResizedSetV3Binary/ConH2781.jpg     H
4   ResizedSetV3Binary/ConH6736.jpg     H
5   ResizedSetV3Binary/ConH3465.jpg     H
6   ResizedSetV3Binary/ConH4526.jpg     H
7   ResizedSetV3Binary/ConH3314.jpg     H
8   ResizedSetV3Binary/ConH3039.jpg     H
9   ResizedSetV3Binary/ConH7061.jpg     H
10  ResizedSetV3Binary/ConH2454.jpg     H
11  ResizedSetV3Binary/ConE1803.jpg     E
12  ResizedSetV3Binary/ConH7315.jpg     H
13  ResizedSetV3Binary/ConH3775.jpg     H
14  ResizedSetV3Binary/ConH6351.jpg     H
15  ResizedSetV3Binary/ConH3024.jpg     H
16   ResizedSetV3Binary/ConE263.jpg     E
17  ResizedSetV3Binary/ConE1003.jpg     E
18  ResizedSetV3Binary/ConE5715.jpg     E
19  ResizedSetV3Binary/ConE5463.jpg     E
20   ResizedSetV3Binary/ConE499.jpg     E
21   ResizedSetV3Binary/ConE739.jpg     E
22  ResizedSetV3Binary/ConE5935.jpg     E
23  ResizedSetV3Binary/ConH4996.jpg     H
24  ResizedSetV3Binary/ConH3791.jpg     H
25  ResizedSetV3Binary/ConH4264.jpg     H
26  ResizedSetV3Binary/ConH7779.jpg     H
27  ResizedSetV3Binary/ConH4847.jpg     H
28  ResizedSetV3Binary/ConH4677.jpg     H
29  ResizedSetV3Binary/ConH7780.jpg     H
30  ResizedSetV3Binary/ConE1503.jpg     E
31  ResizedSetV3Binary/ConH2201.jpg     H
32  ResizedSetV3Binary/ConE1663.jpg     E

In [ ]:
images = [ np.asarray((Image.open(x)), dtype = 'float32')/255  for x in data['Files'] ]

In [ ]:
Y = data.iloc[ : , 1: ]
Y

Label
0      E
1      E
2      E
3      H
4      H
5      H
6      H
7      H
8      H
9      H
10     H
11     E
12     H
13     H
14     H
15     H
16     E
17     E
18     E
19     E
20     E
21     E
22     E
23     H
24     H
25     H
26     H
27     H
28     H
29     H
30     E
31     H
32     E

In [ ]:

enc = OneHotEncoder()

Y = enc.fit_transform(Y).toarray()

Y = pd.DataFrame(Y)

In [ ]:
Y

0    1
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   0.0  1.0
4   0.0  1.0
5   0.0  1.0
6   0.0  1.0
7   0.0  1.0
8   0.0  1.0
9   0.0  1.0
10  0.0  1.0
11  1.0  0.0
12  0.0  1.0
13  0.0  1.0
14  0.0  1.0
15  0.0  1.0
16  1.0  0.0
17  1.0  0.0
18  1.0  0.0
19  1.0  0.0
20  1.0  0.0
21  1.0  0.0
22  1.0  0.0
23  0.0  1.0
24  0.0  1.0
25  0.0  1.0
26  0.0  1.0
27  0.0  1.0
28  0.0  1.0
29  0.0  1.0
30  1.0  0.0
31  0.0  1.0
32  1.0  0.0

In [ ]:
images = np.asarray(images)
images = images.reshape(  len(images), 300, 420, 3 )

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(images,Y, test_size=0.2)

# Model

In [ ]:
model = Sequential()

model.add( Input(shape=(300,420 ,3), dtype="float32"   )  )
model.add(Conv2D(48, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(24, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(24, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(16, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(8, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add( Dense(2, activation='sigmoid')  )


model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_48 (Conv2D)          (None, 298, 418, 48)      1344      
                                                                 
 max_pooling2d_48 (MaxPoolin  (None, 149, 209, 48)     0         
 g2D)                                                            
                                                                 
 conv2d_49 (Conv2D)          (None, 147, 207, 24)      10392     
                                                                 
 max_pooling2d_49 (MaxPoolin  (None, 73, 103, 24)      0         
 g2D)                                                            
                                                                 
 conv2d_50 (Conv2D)          (None, 71, 101, 24)       5208      
                                                                 
 max_pooling2d_50 (MaxPoolin  (None, 35, 50, 24)      

In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy' , 'Recall' , 'Precision'])

# Training

In [ ]:
model.fit( x_train, y_train, epochs=10, batch_size=4, validation_split=0.1)

Epoch 1/10
6/6 [==============================] - 2s 327ms/step - loss: 0.6193 - accuracy: 0.6522 - recall: 0.6522 - precision: 0.6522 - val_loss: 0.7856 - val_accuracy: 0.3333 - val_recall: 0.3333 - val_precision: 0.3333
Epoch 2/10
6/6 [==============================] - 2s 317ms/step - loss: 0.5914 - accuracy: 0.6522 - recall: 0.6522 - precision: 0.6522 - val_loss: 0.7144 - val_accuracy: 0.3333 - val_recall: 0.3333 - val_precision: 0.3333
Epoch 3/10
6/6 [==============================] - 2s 318ms/step - loss: 0.5716 - accuracy: 0.6522 - recall: 0.6522 - precision: 0.6522 - val_loss: 0.6971 - val_accuracy: 0.3333 - val_recall: 0.3333 - val_precision: 0.3333
Epoch 4/10
6/6 [==============================] - 2s 322ms/step - loss: 0.5347 - accuracy: 0.6522 - recall: 0.6522 - precision: 0.6522 - val_loss: 0.6253 - val_accuracy: 0.3333 - val_recall: 1.0000 - val_precision: 0.6000
Epoch 5/10
6/6 [==============================] - 2s 319ms/step - loss: 0.4928 - accuracy: 0.6522 - recall: 0.86

# Evaluation

In [ ]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 161ms/step - loss: 0.0807 - accuracy: 1.0000 - recall: 1.0000 - precision: 1.0000


[0.08069266378879547, 1.0, 1.0, 1.0]

In [ ]:
y_test

0    1
16  1.0  0.0
20  1.0  0.0
13  0.0  1.0
26  0.0  1.0
14  0.0  1.0
17  1.0  0.0
23  0.0  1.0

In [ ]:
model.save('CapacityDetectionV8Binary')

INFO:tensorflow:Assets written to: CapacityDetectionV8Binary/assets


INFO:tensorflow:Assets written to: CapacityDetectionV8Binary/assets


# Prediction

In [ ]:
def get_pred(arg1):
    modelTest = keras.models.load_model('CapacityDetectionV7')

    im = Image.open(arg1)

    imResize = im.resize((300,420), Image.ANTIALIAS)
    imResize.save("TestSpot/TempPic"+'.jpg', 'JPEG', quality=90)

    image1 = np.asarray((Image.open("TestSpot/TempPic.jpg")), dtype = 'float32')/255
    
    image1 = np.asarray(image1)
    image1 = image1.reshape(  1, 300, 420, 3 )        

    result = modelTest.predict(image1)
        
    tClass = result.max()
    
    if(tClass == result[0][0]):
        
        print('Empty')

    if(tClass == result[0][1]):
        
        print('Full')
        
    if(tClass == result[0][2]):
        
        print('High')    

    if(tClass == result[0][3]):
        
        print('Low')
        
    if(tClass == result[0][4]):
        
        print('Middle')   
        
    print(result)

In [ ]:
def get_predBinary(arg1):
    modelTest = keras.models.load_model('CapacityDetectionV8Binary')

    im = Image.open(arg1)

    imResize = im.resize((300,420), Image.ANTIALIAS)
    imResize.save("TestSpot/TempPic"+'.jpg', 'JPEG', quality=90)

    image1 = np.asarray((Image.open("TestSpot/TempPic.jpg")), dtype = 'float32')/255
    
    image1 = np.asarray(image1)
    image1 = image1.reshape(  1, 300, 420, 3 )        

    result = modelTest.predict(image1)
        
    tClass = result.max()
    
    if(tClass == result[0][0]):
        
        print('Low')

    if(tClass == result[0][1]):
        
        print('High')
        
        
    print(result)

In [ ]:
get_pred("ContainerTest/ConE2T.jpg")

1/1 [==============================] - 0s 104ms/step
Empty
[[9.9922609e-01 1.4613991e-12 2.8420231e-05 7.4546947e-04 4.5191118e-09]]


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/1057843181.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


In [ ]:
path = "ContainerTest"
dir_list = os.listdir(path)
 
print("Files and directories in '", path, "' :")
print(len(dir_list))
# Resize all pictures
for item in dir_list:
    print(item)
    get_predBinary("ContainerTest/"+item)

Files and directories in ' ContainerTest ' :
18
ConF8T.jpg
1/1 [==============================] - 0s 102ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.01527466 0.99764377]]
ConE2T.jpg
1/1 [==============================] - 0s 106ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.95560366 0.05945021]]
ConH11T.jpg
1/1 [==============================] - 0s 105ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.02327061 0.949435  ]]
ConL16T.jpg
1/1 [==============================] - 0s 105ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.95161515 0.03787538]]
ConL17T.jpg
1/1 [==============================] - 0s 109ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.96983373 0.02236318]]
ConH10T.jpg
1/1 [==============================] - 0s 109ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.02623441 0.9619203 ]]
ConE3T.jpg
1/1 [==============================] - 0s 106ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.9373973  0.09457061]]
ConF9T.jpg
1/1 [==============================] - 0s 105ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.00938041 0.99907565]]
ConE4T.jpg
1/1 [==============================] - 0s 109ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.9249831  0.08378556]]
ConE5T.jpg
1/1 [==============================] - 0s 109ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.9445499  0.06052072]]
ConL18T.jpg
1/1 [==============================] - 0s 105ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.9715706  0.01630082]]
ConL14T.jpg
1/1 [==============================] - 0s 102ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.94338036 0.0451801 ]]
ConH13T.jpg
1/1 [==============================] - 0s 98ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.00997475 0.9523053 ]]
ConF6T.jpg
1/1 [==============================] - 0s 102ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.08774818 0.98832285]]
ConF7T.jpg
1/1 [==============================] - 0s 101ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.06728277 0.9947006 ]]
ConH12T.jpg
1/1 [==============================] - 0s 102ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


High
[[0.00235259 0.993981  ]]
ConL15T.jpg
1/1 [==============================] - 0s 99ms/step


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)


Low
[[0.970886   0.01995338]]
ConE1T.jpg
1/1 [==============================] - 0s 101ms/step
Low
[[0.93256927 0.0846236 ]]


/var/folders/dh/4qhskwrn31b6sft2hh2sr_nw0000gv/T/ipykernel_9157/2653039182.py:6: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  imResize = im.resize((300,420), Image.ANTIALIAS)
